pipeline {
    agent {label 'slave-1'} 

    environment {
        DOCKERHUB_REPO="harishrajput3/harish-repo"
        DOCKER_CRED_ID="dockerhub-cred"
        GITHUB_URL="https://github.com/harishrajput13/voting-appli-k8-s-pipeline.git"
    }    

    stages {
         stage ('Get Checkout') {
            steps {
                script {
                    git branch: 'main', url: GITHUB_URL, credentialsId: 'git-cred'
                    COMMIT_ID = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    env.IMAGE_TAG = COMMIT_ID
                    echo "Commit id: ${env.IMAGE_TAG}"
                }
            }
        }
 
        stage ('Build Image for vote') {
            steps { 
                script {
                    docker.build ("${DOCKERHUB_REPO}/vote:${IMAGE_TAG}", "vote")
                }
            }
        }
 
        stage ('Build Image for result') {
            steps {
                script {
                    docker.build ("${DOCKERHUB_REPO}/result:${IMAGE_TAG}", "result")
                }
            }
        }

        stage ('Testing vote') {
            steps {
                script {
                    sh 'CID=$(docker run -d -p 8080:80 ${DOCKERHUB_REPO}:${env.IMAGE_TAG})'
                    sh 'docker rm -f $CID || true'
                }
            }
        }

        stage ('Login & Push Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', url: 'https://hub.docker.com/repository/docker/harishrajput3/harish-repo') {
                    sh '''
                        docker.image("${DOCKERHUB_REPO}/vote:${IMAGE_TAG}").push()
                        docker.image("${DOCKERHUB_REPO}/result:${IMAGE_TAG}").push()
                    '''
                }  
                echo "Push ${DOCKERHUB_REPO}/vote:${env.IMAGE_TAG} to DockerHub" 
                echo "Push ${DOCKERHUB_REPO}/result:${env.IMAGE_TAG} to DockerHub"
                }
            }
        }
        
        stage ('Cleanup Docker') {
            steps {
                script {
                    sh 'docker rmi ${DOCKERHUB_REPO}/vote:${env.IMAGE_TAG} || true'
                    sh 'docker rmi ${DOCKERHUB_REPO}/result:${env.IMAGE_TAG} || true'
                }
            }
        }
    }

    post {
        success {
            echo "Image ${DOCKERHUB_REPO}/vote:${env.IMAGE_TAG} Sucessfully"
            echo "Image ${DOCKERHUB_REPO}/result:${env.IMAGE_TAG} Sucessfully"
        }
        failure {
            echo "Pipeline is failed, check logs"
        }
    }
}
